const fs = require('fs');
const path = require('path');

// Extract core logic from index.html in the parent directory
const htmlPath = path.join(__dirname, '../index.html');
const outputPath = path.join(__dirname, 'temp_test_core.js');

if (!fs.existsSync(htmlPath)) {
    console.error('Error: index.html not found at ' + htmlPath);
    process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const scriptMatch = html.match(/<script>([\s\S]*?)<\/script>/);

if (!scriptMatch) {
    console.error('Error: No script block found in index.html');
    process.exit(1);
}

let code = scriptMatch[1];

// Surgical removal of DOM-related startup code
const cutoff = code.indexOf('buildWeights();');
if (cutoff !== -1) {
    code = code.substring(0, cutoff);
}

// Mock browser environment for Node.js
const mockDom = `
const $ = (id) => ({
    value: '0',
    textContent: '',
    innerHTML: '',
    classList: { add: () => {}, remove: () => {} },
    querySelector: () => ({ innerHTML: '' }),
    querySelectorAll: () => [],
    addEventListener: () => {}
});
const document = {
    getElementById: $,
    querySelectorAll: () => [],
    createElement: () => ({ innerHTML: '', appendChild: () => {} }),
    querySelector: () => null
};
const window = {
    addEventListener: () => {},
    devicePixelRatio: 1,
    scrollTo: () => {}
};
const localStorage = { setItem: () => {}, getItem: () => null };
const sessionStorage = { setItem: () => {}, getItem: () => null };
const location = { reload: () => {} };
const navigator = { language: 'zh-TW' };
const canvas = { getContext: () => ({ setTransform: () => {}, clearRect: () => {}, beginPath: () => {}, arc: () => {}, fill: () => {}, moveTo: () => {}, closePath: () => {}, stroke: () => {}, fillText: () => {}, lineTo: () => {}, setLineDash: () => {} }) };
const Image = class {};
`;

// Remove browser-specific declarations that might conflict
code = code.replace(/const \$=id=>document\.getElementById\(id\);/, '// removed $');
code = code.replace(/"use strict";/, '');

const finalCode = `
// Auto-generated by extract_logic.js for independent testing
${mockDom}
${code}
module.exports = { simulate, milestones, assetDefs, percentile, impliedCAGR, l2muNom };
`;

fs.writeFileSync(outputPath, finalCode);
console.log('✅ Core logic successfully extracted to: ' + outputPath);
